#!/usr/bin/env bash

VERSION=$(cat .node-version)
DIR_NAME=.node-installation
CACHE_FN=".node-v$VERSION-linux-x64.tar.gz" 
PREAMBLE=$'#!/usr/bin/env bash\nNODE_PATH=$PWD/.node-installation/bin/'
echo "Installing NodeJS ($VERSION)."
if [ -e $CACHE_FN ]; then
	echo "Found $CACHE_FN. Skipping download."
else
	echo "Cache $CACHE_FN not found. Downloading..."
	wget --no-verbose https://nodejs.org/dist/v$VERSION/node-v$VERSION-linux-x64.tar.gz
	mv node-v$VERSION-linux-x64.tar.gz .node-v$VERSION-linux-x64.tar.gz
fi
rm -rf $DIR_NAME
tar -xzf .node-v$VERSION-linux-x64.tar.gz 
mv node-v$VERSION-linux-x64 $DIR_NAME
#rm node 2> /dev/null
echo "$PREAMBLE $PWD/.node-installation/bin/node \"\$@\"" > node
chmod +x node
echo "$PREAMBLE $PWD/.node-installation/bin/node $PWD/.node-installation/bin/npm \"\$@\"" > npm
chmod +x npm
echo "DONE. Created ./node and ./npm entry points."
#rm npm 2> /dev/null
#ln -s $DIR_NAME/bin/node node
#ln -s $DIR_NAME/bin/npm npm
